### ISSUE TITLE
Add sort to dataset list

### ISSUE THREAD

**Issue by knutole** [systemapic/systemapic.js#102]
_Moved here from https://github.com/systemapic/wu/issues/259_
- [ ] `sort`: make dataset list sortable (with quick buttons - name, modified, size)
- [ ] `filter`: create "quick-search" box (<input> with filter, showing only matches in list)
- [ ] put boxes over first dataset-line  

![screen shot 2016-01-04 at 6 18 36 pm](https://cloud.githubusercontent.com/assets/2197944/12095544/9d5f00ae-b30f-11e5-87b4-b3f1436c9b13.png)

see also #255

**Comment by knutole** [comment]
@IgorZiegler :)

**Comment by jorgenevil** [comment]
This should be fairly simple, as the list is written in D3. All you have to do is updating the array of files, and run the list again.

I also think the sorting features should only appear if you have more than 10 files in your library.

**Comment by jorgenevil** [comment]
One thing that I also would have liked to see in the sort feature, is the ability to view files that's been added as layers in _current project_. I don't know if this is a big task, but I think it would be nice :)

**Comment by jorgenevil** [comment]
Here is a design suggestion of how sort and search can be mixed together to avoid cluttering.

![sort filter](https://cloud.githubusercontent.com/assets/8961926/13106436/7c7431cc-d568-11e5-979b-9e4cc0dc24ed.jpg)

**Comment by knutole** [comment]
I say, go for it! :) Looks great! 

Btw, I think it should always be there! It looks unintrusive:)

**Comment by IgorZiegler** [comment]
@knutole @jorgenevil  How will looks sort input when it expanded?

**Comment by IgorZiegler** [comment]
@knutole @jorgenevil looks cool. I begin do it without this design =(

**Comment by jorgenevil** [comment]
I'll design it!

**Comment by jorgenevil** [comment]
Something like this:
![sort-expanded](https://cloud.githubusercontent.com/assets/8961926/13107195/bc39b4e0-d56c-11e5-8561-173cd6f20967.jpg)

**Comment by jorgenevil** [comment]
Our data library have the option to have more than one file provider, even thought we only have one now, which is called _postgis_. This is for other kinds of file types in the future.

In `chrome.data.js`, you can see how we populate `this.fileProviders.postgis` here:
https://github.com/systemapic/systemapic.js/blob/master/js/src/chrome/data/chrome.data.js#L379

Files gets populated with data here, which puts data into an array (`this.fileProviders['postgis'].data`):
https://github.com/systemapic/systemapic.js/blob/master/js/src/chrome/data/chrome.data.js#L408

If you have a sorted array of data, you can store it on `this.fileProviders['postgis'].data`, and run this:

```
var D3container = this.fileListContainers['postgis'].D3container;
var data = this.fileProviders['postgis'].data;
this.initFileList(D3container, data, 'postgis');
```

To clear sorting, and get the original files back, you can do this by running `this._refreshFiles()`

**Comment by knutole** [comment]
fixed. great job @IgorZiegler ! :+1:
