### ISSUE TITLE
Loooooong project names makes client look weird

### ISSUE THREAD

**Issue by knutole** [systemapic/systemapic.js#103]
![screen shot 2016-02-16 at 10 34 01 pm](https://cloud.githubusercontent.com/assets/2197944/13092097/913c21c4-d4fe-11e5-9fce-4a2786bcda6b.png)

Guess we need to cut down on the overflow.

**Comment by jorgenevil** [comment]
I suggest we trim the title length in JS, and don't chop the overflow with CSS. It just looks better not to have letters cut in half :)

The min-width of the site is 1120px, which means that we have room for 13 characters, or 12 characters + three dots.

I've tested this with a capital `M`, one of the widest characters.

![screen shot 2016-02-16 at 10 54 09 pm](https://cloud.githubusercontent.com/assets/8961926/13092511/a9beed4c-d500-11e5-86e4-e2400cbdfb7a.png)
![screen shot 2016-02-16 at 10 57 18 pm](https://cloud.githubusercontent.com/assets/8961926/13092549/d5f194f0-d500-11e5-8045-9ae793f626df.png)

**Comment by knutole** [comment]
on it

**Comment by jorgenevil** [comment]
Would have been cool in to have a window resize listener on it in the future, so that we don't have to restrict our users to have short project names. But that's no a priority.

**Comment by knutole** [comment]
done :+1:
