### ISSUE TITLE
remove requests for /css/images/icons-000000@2x.png

### ISSUE THREAD

**Issue by knutole** [systemapic/systemapic.js#104]
From whence do they come? @jorgenevil ?

![screen shot 2016-02-16 at 11 02 08 pm](https://cloud.githubusercontent.com/assets/2197944/13092635/5450bace-d501-11e5-82fb-fb32db494b4f.png)

They are not "found", so probably not needed - should preferably be removed.

**Comment by jorgenevil** [comment]
That is leaflet icons for retina display. Gets called from CSS somewhere. I'll look into it.
