### ISSUE TITLE
bigger text on popup?

### ISSUE THREAD

**Issue by knutole** [systemapic/systemapic.js#127]
Text is really quite small now. Perhaps twice as big and put each key/value on same line?

![screen shot 2016-02-19 at 5 16 05 pm](https://cloud.githubusercontent.com/assets/2197944/13181268/8662964a-d72c-11e5-914d-bb07ffe9f3c5.png)

**Comment by jorgenevil** [comment]
I agree. It would also be nice to have the option to have pop up appear on point + option for popup on hover.

**Comment by knutole** [comment]
Yeah, should make a separate issue for that.

**Comment by knutole** [comment]
fixed somewhat. not the pretties, but more legible.

![screen shot 2016-02-20 at 2 20 24 pm](https://cloud.githubusercontent.com/assets/2197944/13196897/216aaa82-d7dd-11e5-9e78-d556b9bc20b9.png)

@jorgenevil CSS rules put in bottom of `knut.css` - but this is after the funky merge, so make sure you don't delete whole file! :)  Plus, the suggestions above should go in separate issue. Closing this
