### ISSUE TITLE
Popup styling

### ISSUE THREAD

**Issue by jorgenevil** [systemapic/systemapic.js#134]
• Forcing a fixed width for column key is problematic if key name is longer than the given space.
• If value is longer than one line, it will end up on a separate line.

![screen shot 2016-02-22 at 2 17 15 pm](https://cloud.githubusercontent.com/assets/8961926/13219271/3a55627e-d96f-11e5-90c6-05bf7703225f.png)

There are two solutions:
a) Have key and value on separate lines, like before
b) Have key on the same line as value, but not force a given width.

I think solution a) looks better.

**Comment by knutole** [comment]
Could also create the two columns as separate columns - ie. make the long line cut only in right column? I don't think we should go back to two lines, it's messy.

**Comment by jorgenevil** [comment]
I don't think two lines are messy.

**Comment by knutole** [comment]
fixed

![screen shot 2016-02-22 at 3 57 07 pm](https://cloud.githubusercontent.com/assets/2197944/13221685/f1634992-d97c-11e5-9f1b-e767e1b6460c.png)
