### ISSUE TITLE
Popup-chart meta should be in three columns

### ISSUE THREAD

**Issue by knutole** [systemapic/systemapic.js#141]
And not like this:
![screen shot 2016-02-22 at 9 06 00 pm](https://cloud.githubusercontent.com/assets/2197944/13231016/1b7f44e4-d9a8-11e5-9f04-1abbe3d6bd45.png)

Bug introduced with this commit: https://github.com/systemapic/systemapic.js/commit/4a9cc64a5054884d071dd7c00773f334d6a52fb8

**Comment by jorgenevil** [comment]
Three columns:

![screen shot 2016-02-22 at 9 34 40 pm](https://cloud.githubusercontent.com/assets/8961926/13231800/1c6a9e54-d9ac-11e5-83ab-ef52245d0f48.png)
