### ISSUE TITLE
Clean up chrome header if last project is deleted

### ISSUE THREAD

**Issue by jorgenevil** [systemapic/systemapic.js#148]
Tiny bug, but title does not clean up if last project is deleted.

![screen shot 2016-02-23 at 2 12 25 pm](https://cloud.githubusercontent.com/assets/8961926/13252520/8391d7a6-da37-11e5-818f-969a4face539.png)

**Comment by knutole** [comment]
This bug will go away when we implement scratchpad (ie. never zero projects).

So closing.
