### ISSUE TITLE
Upload bug is back – utf8

### ISSUE THREAD

**Issue by jorgenevil** [systemapic/systemapic.js#149]
Wasn't this bug fixed? Now I cannot upload any of my files again.

![screen shot 2016-02-23 at 2 20 27 pm](https://cloud.githubusercontent.com/assets/8961926/13252742/aa89854c-da38-11e5-9341-7bc0c5b4cb12.png)

**Comment by knutole** [comment]
Related to https://github.com/systemapic/wu/issues/464

**Comment by knutole** [comment]
Closed in favor of https://github.com/systemapic/wu/issues/464
