### ISSUE TITLE
Not possible to add data as layers

### ISSUE THREAD

**Issue by jorgenevil** [systemapic/systemapic.js#150]
This must have happened since the last merge, but right now, I cannot add any layers to a project.

![screen shot 2016-02-23 at 2 23 24 pm](https://cloud.githubusercontent.com/assets/8961926/13252851/319f4404-da39-11e5-8237-42163d1be623.png)

**Comment by knutole** [comment]
@jorgenevil Try uploading file again, could be a bug with the uploading that caused this.

**Comment by knutole** [comment]
This is a [pile](https://github.com/systemapic/pile) bug, btw, since `/v2/tiles/create` point to the pile tileserver (see API documentation https://github.com/systemapic/wu/issues/424).

**Comment by jorgenevil** [comment]
This happens on beta as well – where I try to add data that I have uploaded before, and that I have added to other projects.

**Comment by knutole** [comment]
Yeah, that's FUBAR.

Try to include logs from server in issue for these bugs.

**Comment by jorgenevil** [comment]
Looks like an unexpected token from last merge? 

![screen shot 2016-02-23 at 2 35 54 pm](https://cloud.githubusercontent.com/assets/8961926/13253142/d3b71626-da3a-11e5-92ed-affb7ac3f1d1.png)

**Comment by knutole** [comment]
@jorgenevil `./restart.sh` your server and try to get the bug above again.

**Comment by knutole** [comment]
@jorgenevil Updated a bit, seems to work fine on beta now. Can you reproduce this bug on `mx` or beta?

**Comment by jorgenevil** [comment]
It works on `beta` now! On `MX` I can't do it, as the files I have in the library gets an error that probably has to do with the fact that I uploaded them ages ago – and I cannot upload new data, as I get UTF bug.
