### ISSUE TITLE
New project should not come with users

### ISSUE THREAD

**Issue by jorgenevil** [systemapic/systemapic.js#154]
When I create a project, it comes with 6 users without me doing anything:

![screen shot 2016-02-24 at 2 22 01 pm](https://cloud.githubusercontent.com/assets/8961926/13286481/03792e54-db02-11e5-8386-71337123675c.png)

**Comment by knutole** [comment]
@jorgenevil Can you check again now? Pretty sure this is fixed. If so, please close.

**Comment by knutole** [comment]
@jorgenevil ????
