### ISSUE TITLE
Project title user count features

### ISSUE THREAD

**Issue by jorgenevil** [systemapic/systemapic.js#156]
- [x] Only editors should see how many people that has access to the project
- [x] Give basic information on hover, like there is with public projects

![screen shot 2016-02-24 at 3 51 41 pm](https://cloud.githubusercontent.com/assets/8961926/13288966/864e438a-db0e-11e5-8ed0-bc3ec21ef86e.png)

**Comment by knutole** [comment]
Yes, cool. This could work:

``` javascript
if (project.isEditor()) {
  // logged in user is editor of project
}
```

**Comment by knutole** [comment]
@jorgenevil  This number needs to be updated after adding more people to project. Best would be to use a listener.

We can close this issue afterwards.

**Comment by IgorZiegler** [comment]
@knutole @jorgenevil what does mean  Give basic information on hover ? Is it mean that when i click on public project it should so something?

**Comment by knutole** [comment]
@IgorZiegler 

Hover - means when you hold the mouspointer over an area (but not clicking)... 

So "give basic info on hover" means simply when hovering over the cirle with `(42)` (see image above), and tooltip message should pop up say, "The project is currently shared with 42 people."

For hovering, see how it's done with the other hover's in project list.

**Comment by knutole** [comment]
@IgorZiegler Nice.

I see you've added callbacks, etc... As mentioned above, the best way would be to do this with listeners. Meaning, that `chrome.projects.js` listens for `projectUpdated` (which you must fire after updating), and THEN it can update the list... We want to move towards implementing more event listeners, so it would be better to do it that was. (See top of `chrome.js` for example of listeners.)  
- [x] updating count number after edit - works!
- [x] hover on count number to get tooltip

![hover_user](https://cloud.githubusercontent.com/assets/2197944/13433051/80f2b53a-dfd0-11e5-9602-9c877785f163.gif)
