### ISSUE TITLE
Prevent creating multiple projects

### ISSUE THREAD

**Issue by jorgenevil** [systemapic/systemapic.js#157]
It takes a second or so to create a new project. If you click many times on the `create` button while creating a project, it creates multiple projects with the same name. We need to prevent this from happening.

![screen shot 2016-02-24 at 4 51 24 pm](https://cloud.githubusercontent.com/assets/8961926/13291131/e193037c-db16-11e5-8cd9-286646df9c81.png)

**Comment by jorgenevil** [comment]
Problem seen as a gif :P
![multiple-projects](https://cloud.githubusercontent.com/assets/8961926/13293821/9c01098e-db21-11e5-95bc-6bf0f10b9574.gif)

**Comment by knutole** [comment]
You can add a simple blocker on the create button until created project is ready :)
