### ISSUE TITLE
Zoom to raster layer is to wrong extent 

### ISSUE THREAD

**Issue by strk** [systemapic/systemapic.js#162]
May be related to the upside-down problem recently fixed but I see the map zoomed to the wrong extent on raster import (map goes to a tiny upper-left corner of the actual raster extent).

@knutole

**Comment by knutole** [comment]
Hum, for which dataset? My zoom-to-extent is actually working perfectly fine? (with snow raster)

**Comment by strk** [comment]
Found the culprit, my fault. Will handle in https://github.com/systemapic/wu/issues/481
