### ISSUE TITLE
Mismatch between available users and users which have access to the project

### ISSUE THREAD

**Issue by IgorZiegler** [systemapic/systemapic.js#163]
Sometimes  in [line](https://github.com/systemapic/systemapic.js/blob/bc9f6123f612497722c6d751647aecaaa9cdd827/js/src/chrome/projects/chrome.projects.js#L992) we have `user-a3eef95c-f46a-407c-8109-b62fb36badf2` in `userUuid` variable, but `app.Users[userUuid]` doesn't exist.

Not sure why it is happen. May be user was deleted or wasn't added.

**Comment by knutole** [comment]
This is due to deleted users. Closing as we have tickets for proper deleting of users elsewhere.
