### ISSUE TITLE
Create "accept contact request" success page

### ISSUE THREAD

**Issue by knutole** [systemapic/systemapic.js#164]
When user asks for contact, the contact receives an email with request to accept. When accepting, contact is redirected to an empty page with a simple "ok" message. 
- [ ] Need to add something more meaningful (perhaps account page with feedback message)

**Comment by IgorZiegler** [comment]
@knutole How should it looks?

**Comment by knutole** [comment]
OK, this one we can make very simple. Just a page with a centered logo, and a message. 

Also a ten-seconds redirect to `/`... with a message saying, "Redirect to main page in 10..9..8.." etc.

**Comment by IgorZiegler** [comment]
@knutole How can i send request for add contact?
