### ISSUE TITLE
Should not be possible to add user to EDIT access if not editor

### ISSUE THREAD

**Issue by knutole** [systemapic/systemapic.js#166]
It's currently possible in GUI to add a user as `editor` to a project which user does not have edit access to.  This should not be possible.

![invite_editor](https://cloud.githubusercontent.com/assets/2197944/13374122/e320028c-dd7b-11e5-88e8-3521c6faeda3.gif)

**Comment by IgorZiegler** [comment]
@knutole if user haven't edit access rights. Could he add a user as viewer?

**Comment by knutole** [comment]
That depends on if the project is shareable, ie. this key: https://github.com/systemapic/wu/blob/master/models/project.js#L26

Use `project.isShareable()` to get this key.  If `project.isShareable()` is true, then a VIEWER can invite other VIEWERS.

**Comment by IgorZiegler** [comment]
@knutole Ok. How could i create a second user? Which script should I use?

**Comment by IgorZiegler** [comment]
@knutole I have a problem when try reproduce this bug. I have created project, invite a new user to this project as a viewer. sign in as new user. and it is impossible to add my contact as editor or viewer.

**Comment by knutole** [comment]
Yes, possibly fixed. Will reopen if issue appears again.
