### ISSUE TITLE
optimize bigslider

### ISSUE THREAD

**Issue by knutole** [systemapic/systemapic.js#191]
#### 1. Draw gray area only once

Ser ut som hele det grå området blir redrawn for hver frame? Se [denne](https://github.com/systemapic/systemapic.js/blob/master/js/src/panes/pane.bigslider.js#L400) console loggen: 

``` javascript
        // Rebuild graph data
        this.years[year].forEach(function (d, i) {

            if ( d.Doy < day ) {
                console.log('rebuild graph data');  // <- 
                d.date = this._dateFromNo(i)
                this.graphData.push(d);
            }

        }.bind(this));
```

![screen shot 2016-03-31 at 12 52 45 am](https://cloud.githubusercontent.com/assets/2197944/14160167/f8ba3a36-f6da-11e5-8b49-3e1f3c7306f9.png)

Antall loops per frame:
![slider-redraws](https://cloud.githubusercontent.com/assets/2197944/14160784/07f49a1a-f6df-11e5-894e-0bce2496b8ca.gif)

Forslag: draw gray area only once. Og minimere så mye som mulig operasjoner - spesielt looper og lesing av mye data. På animation, så bør kun den rød trekanten flytte på seg og den rød streken tegnes.
#### 2. Fetching of `allYears` data

Jeg prøvde å gjøre noe lurt der, med å kun hente data én gang, men funka ikke. Jeg skal fikse dette. Skal også gjøre om på at `bigSlider` blir callet fra layer, det var en dårlig idé.

**Comment by jorgenevil** [comment]
`Rebuild graph data` endrer ikke på det grå området. Det er kun `this.graphData` som blir endret, og det inneholder kun årets data (maks 365 dager).
