### ISSUE TITLE
bigslider bugs

### ISSUE THREAD

**Issue by knutole** [systemapic/systemapic.js#192]
#### 1. mange slider "håndtak", skal vel bare være ett?

![slider-bug-1](https://cloud.githubusercontent.com/assets/2197944/14160974/518c0a2c-f6e0-11e5-917d-41e3728db7f7.gif)
#### 2. når man trykker PLAY, men er på slutten av serien, så kommer det allikevel PAUSE ikon

![slider-bug-2](https://cloud.githubusercontent.com/assets/2197944/14161017/9cfe3660-f6e0-11e5-886b-0c9bf2b373cc.gif) Kan også ha 1. jan som default start-posisjon, sånn at bruker slipper å flytte slider før han trykker play.
#### 3. Forslag: legge slider sammen med chart

Slider og chart tar begge vel mye plass. Kan legge slider på bunnen av charten, trenger ikke være større.
Jan-Des er representert på begge sliders, så matcher jo bra. Vi trenger strengt tatt ikke ha "dynamisk" slider, men kan istedet ha den fra jan-des uansett, og hoppe på år, slik charten gjør. Kan trimme mye white-space.

**Comment by knutole** [comment]
@jorgenevil Hva tenker du om å gjøre slider/chart litt mer kompakt? Og sånn at slideren følger den røde trekanten ift. måned? (Stylinga over er bare drag-n-droppa slider-div inn i chart-div, med width 95%, pos abs og zoom 0.5) 
![compact-slider](https://cloud.githubusercontent.com/assets/2197944/14225838/699b3604-f8d1-11e5-9baa-7c17bd2ee924.gif)

**Comment by jorgenevil** [comment]
Ja, det er kanskje praktisk å ha dem sammen...

Men litt av problemet med å ha X-aksen sammen med tidslinjen, er at x-aksen alltid representerer Januar til Januar, mens tidslinjen kun representerer 365 dager, uavhengig om man starter i Mars eller i Oktober.

Men det finnes sikkert en workaround til det. Kan se på det.

**Comment by knutole** [comment]
Ja, la merke til det. En mulighet er kanskje å låse tidslinjen fra jan-des også?

**Comment by jorgenevil** [comment]
Tja, men da vil man jo ikke få 365 dager på linja. La oss si at vi er i Februar – da vil tidslinja kun vise Januar til Februar. Men det gjør kanskje ikke noe?
