### ISSUE TITLE
zooming on chart is buggy

### ISSUE THREAD

**Issue by knutole** [systemapic/systemapic.js#20]
When mousescroll-zooming on chart, something is buggy - at least some of the time. Scrolls too fast. Need to look at the algorithm for scrolling.

**Comment by knutole** [comment]
@IgorZiegler You could have a look at this one at the same time :+1:

**Comment by IgorZiegler** [comment]
@knutole Unfortunately I did not catch this task. Could you provide some example?

**Comment by knutole** [comment]
Yes, unfortuneately a bit hard to reproduce. This does not happen on all data, just some. Will try to find a dataset which is buggy, and post here.

But the bug is that when you "mousescroll" on the chart, it will zoom. This works well most of the time, but sometimes it's buggy and it will zoom to infitiny, etc.

![screen shot 2016-02-16 at 8 48 05 am](https://cloud.githubusercontent.com/assets/2197944/13070532/87b17d1e-d48d-11e5-9a93-361503196d7f.png)
