### ISSUE TITLE
Pad/mobile: when tilting, screen size is not updated

### ISSUE THREAD

**Issue by knutole** [systemapic/systemapic.js#207]
> " it seems there is a small bug related to the viewer. When I have it on the long side it doesnt fill out. Works when I tilt it again.""

Need to update screen size when tilting screen.

**Comment by jorgenevil** [comment]
Solution is to register event for tilting on screen, and run same update script as we do when resizing window.

**Comment by knutole** [comment]
@jorgenevil Får du fiksa det?

**Comment by jorgenevil** [comment]
I mårra.
