### ISSUE TITLE
Pad/mobile: login button is not available

### ISSUE THREAD

**Issue by knutole** [systemapic/systemapic.js#208]
Login button is hidden on mobile/pad. So no way for user to log in on mobile.

**Comment by jorgenevil** [comment]
Can we have confirmed that this is true for pad? I cannot reproduce this issue for pad.
As for mobile, the admin part of the site is not optimized for mobile view – only the public version.

**Comment by knutole** [comment]
@jorgenevil  Ikke sikker om det her er for pad, faktisk.

Men folk må kunne logge seg inn og se private prosjekter, selv om de ikke kan redigere, etc. Får du fiksa det?

**Comment by jorgenevil** [comment]
Hele prosjektmenyen må da designes for mobil. Vil ta 4-6 timer. Rekker nok ikke det før til uka.
