### ISSUE TITLE
adjustments to satellite meta boxes

### ISSUE THREAD

**Issue by knutole** [systemapic/systemapic.js#30]
> jeg har gjort en lit feil på figuren lengst nede til høyere
> i steden for ordet "satellittkurs" så sku det vært "sikteretning"
> og en annen justering:
> under figuren målevinkel, kunne dere lagt på en "arrow" mot bakken slik at man skjønner at målingen går den veien
- [x] "sikteretning"
- [ ] arrow

**Comment by knutole** [comment]
@jorgenevil vår venn på labben kom med disse forslagene. fort gjort?

**Comment by jorgenevil** [comment]
On it, men ganske slitsomt å tegne opp SVG path for arrow. Det er et fuckings regnestykke som det tar litt tid å wrappe huset sitt rundt, så jeg tar det i kveld.

**Comment by knutole** [comment]
@jorgenevil får du fiksa denne i helga? så `px`en kan få det til mandag?
