### ISSUE TITLE
Allow overflow in pop-up

### ISSUE THREAD

**Issue by jorgenevil** [systemapic/systemapic.js#31]
Do not restrict height of fields.

![screen shot 2016-02-04 at 4 35 40 pm](https://cloud.githubusercontent.com/assets/8961926/12820235/86d301ac-cb5e-11e5-9b0e-41b821ab4361.png)

**Comment by knutole** [comment]
@jorgenevil fixed?

**Comment by jorgenevil** [comment]
yes
