### ISSUE TITLE
layermenu sometimes turns invisible

### ISSUE THREAD

**Issue by jorgenevil** [systemapic/systemapic.js#33]
Sometimes parts of the layer menu turns invisible.

![screen shot 2016-02-04 at 4 48 53 pm](https://cloud.githubusercontent.com/assets/8961926/12820405/32c78564-cb5f-11e5-9919-e8e6eb8b6fcf.png)

**Comment by jorgenevil** [comment]
Is this still a problem? I haven't seen it in a long while. Have you @knutole?

**Comment by knutole** [comment]
Haven't seen it, no.

**Comment by jorgenevil** [comment]
I think this has been fixed with the calculations of scrollers, so I will close it.
