### ISSUE TITLE
Create pretty dropdown instead of basic <select> dropdown

### ISSUE THREAD

**Issue by knutole** [systemapic/systemapic.js#42]
Need a pretty dropdown - not the default ugly `<select>` dropdown. Should be created from scratch as `Wu.Dropdown` class, and take content as options param on creation.
- [x] create new file with `Wu.Dropdown` class
- [x] change old dropdown for baselayers (under Data tab)
- [x] change dropdowns in Styler

Dropdown should be created thus:

``` javascript
var pretty_dropdown = new Wu.Dropdown({
    content : ['layer1', 'layer2'],
    fn : this._dropdownSelected // function runs when dropdown item selected
})
```

New file can be put in `/js/src/ext/dropdown.js`, and built like this:

``` javascript
Wu.Dropdown = Wu.Class.extend({

   // this function will run automatically on new Wu.Dropdown()
   initialize : function (options) {
      Wu.setOptions(this, options); // will put options in this.options

   },

   build : function () {
      var content = this.options.content;
   },
});
```

**Comment by IgorZiegler** [comment]
@knutole `change old dropdown for baselayers (under Data tab)` Do you mean Background layer?

**Comment by IgorZiegler** [comment]
@knutole https://github.com/systemapic/systemapic.js/pull/88/files

**Comment by IgorZiegler** [comment]
Also we need add `appendTo` in option.
