### ISSUE TITLE
"Set bounds" not clearing when changing projects

### ISSUE THREAD

**Issue by jorgenevil** [systemapic/systemapic.js#57]
Sometimes (quite often), the bounds does not refresh when I'm changing projects, meaning that I'm not allowed to go to the area of interest in the project. I have to set and clear bounds to refresh properly.

**Comment by knutole** [comment]
Can you tell me more specifically steps to reproduce?

**Comment by jorgenevil** [comment]
If I'm at a project that has BOUNDS set – and I go to another project (that does not have bounds set), sometimes the bounds from the previous project 'hangs' on to the new one.

**Comment by knutole** [comment]
##### Additional bug:
- not possible to zoom down to z20 if bounds is set... apparently

**Comment by knutole** [comment]
working on this now
