### ISSUE TITLE
small fixes for legends- and popup box

### ISSUE THREAD

**Issue by knutole** [systemapic/systemapic.js#58]
- Looks like perhaps the second, third item does not get its content description included (only title)?
  ![screen shot 2016-02-12 at 12 13 09 pm](https://cloud.githubusercontent.com/assets/2197944/13005474/841cd36e-d182-11e5-9b0f-c7175e29488e.png)
- Perhaps wrap this legend with a border or something, make it look a bit more "set." Also, it's a bit unaligned vertically.
  ![screen shot 2016-02-12 at 12 12 42 pm](https://cloud.githubusercontent.com/assets/2197944/13005503/a1dd4a64-d182-11e5-8064-bd9226ddb460.png)
- Perhaps move the opacity slider to one line. As it is now, it takes up too much space.
  ![screen shot 2016-02-12 at 12 19 09 pm](https://cloud.githubusercontent.com/assets/2197944/13005543/db121508-d182-11e5-86e7-a0d3fc74c2ae.png)

**Comment by knutole** [comment]
Should perhaps remove this function also, and keep all css in one place: https://github.com/systemapic/systemapic.js/blob/master/js/src/panes/pane.map.js#L378 ??

**Comment by knutole** [comment]
@jorgenevil Can close this if fixed..?

**Comment by jorgenevil** [comment]
Not quite there yet :P

**Comment by knutole** [comment]
- [x] Fixed opacity slider to one line.

**Comment by knutole** [comment]
This seems all fixed. @jorgenevil ?? Let's close it!
