### ISSUE TITLE
share <input> bugs

### ISSUE THREAD

**Issue by knutole** [systemapic/systemapic.js#64]
1. When writing beginning of a name, "Jo..", then "jorgen" is highlighted. However, if pressing [Enter], "Igor" is selected. (This is for sharing "Spectators of project" when editing project.)

![screen shot 2016-02-12 at 2 42 28 pm](https://cloud.githubusercontent.com/assets/2197944/13008492/e864a98c-d196-11e5-9e4e-40703269fbd1.png)
![screen shot 2016-02-12 at 2 42 31 pm](https://cloud.githubusercontent.com/assets/2197944/13008494/ea6ffde4-d196-11e5-916c-89f7eabf9b43.png)

**Comment by knutole** [comment]
1. User added as EDITOR, can't be removed afterwards, if user is the one who created the project. 
   ![screen shot 2016-02-12 at 2 47 09 pm](https://cloud.githubusercontent.com/assets/2197944/13008631/a3e8b3d8-d197-11e5-9ab1-9634e81d65fc.png)

This is a logical error. The user who owns the project shouldn't be available on the list, because adding the owner as READER or EDITOR doesn't make sense.
- [ ] filter out project_owner from READER/EDITOR lists

**Comment by knutole** [comment]
@IgorZiegler Are all these fixed?

**Comment by IgorZiegler** [comment]
@knutole I think yes
