### ISSUE TITLE
legends bug

### ISSUE THREAD

**Issue by knutole** [systemapic/systemapic.js#67]
> first problem: Style->select layer -> no tiles, console contains TypeError: Wu.Legend is not a constructor
> this._legendStyler = new Wu.Legend(legendOptions);
> that's line 98 of chrome.settings.styler.js
> this._legendStyler = new Wu.Legend(legendOptions);
> if I click on the error shown in console, firebog takes me to the "Script" tab, showing the code

`Uncaught TypeError: Wu.Legend is not a functionListPicker._handleMouseUp @ about:blank:504`

**Comment by strk** [comment]
![screenshot from 2016-02-12 16 53 22](https://cloud.githubusercontent.com/assets/289678/13011952/8675d54e-d1a9-11e5-9a08-c120b92d0982.png)

**Comment by knutole** [comment]
fixed by pulling latest `wu` and manually `./restart.sh`ing
