### ISSUE TITLE
css overflow on chart

### ISSUE THREAD

**Issue by knutole** [systemapic/systemapic.js#69]
Regression on bottom falls outside frame. Probably due to many columns listed on top.

![screen shot 2016-02-13 at 12 19 54 am](https://cloud.githubusercontent.com/assets/2197944/13023256/8e778682-d1e7-11e5-9faf-67957cb3d4b2.png)

**Comment by IgorZiegler** [comment]
@knutole  How can I get this chart?

**Comment by knutole** [comment]
Upload this file:
[InSARAkersvatn2013-14.tar.gz](https://github.com/systemapic/systemapic.js/files/131009/InSARAkersvatn2013-14.tar.gz)

**Comment by knutole** [comment]
@IgorZiegler status on this one?

**Comment by knutole** [comment]
This is fixed with scrollers. closing.
