### ISSUE TITLE
Clicking draw toolbar twice should close it

### ISSUE THREAD

**Issue by knutole** [systemapic/systemapic.js#70]
Currently, it won't close on second click on toolbar icon.
![screen shot 2016-02-13 at 12 22 07 am](https://cloud.githubusercontent.com/assets/2197944/13023290/d610b3a6-d1e7-11e5-9e61-170e8d1f78fe.png)

**Comment by IgorZiegler** [comment]
@knutole I have a problem with find solution. I don't understand how we can handle click event.
