### ISSUE TITLE
Save styling on dataset (not only on layer)

### ISSUE THREAD

**Issue by jorgenevil** [systemapic/systemapic.js#71]
It's getting quite annoying that I have to spend lots of time styling layers over and over again. 

It would be very nice to be able to have my data styles, so that i can browse through my pre designed layers when creating a project.

I discussed this with Knut, and i think the best option is to have a list of active stylesheets collected from the projects where this data is loaded as a layer. You may also want to choose one master stylesheet, so that you have a pre designed "template style" that you can work from. This is also interesting when sharing a dataset.

**Comment by knutole** [comment]
Should be pretty simple to implement:
- Create a new key on [file model](https://github.com/systemapic/wu/blob/master/models/file.js#L29) 

``` javascript
styleTemplates : [String] // array of JSON strings
```
- add get/set on [`model.file.js`](https://github.com/systemapic/systemapic.js/blob/master/js/src/models/model.files.js#L24)

``` javascript

// get all templates
getStyleTemplates: function () {
   return this.store.styleTemplates; // array
},

// set all templates
setStyleTemplates : function (templates) {
   this.store.styleTemplates = templates; // array
   this.save('styleTemplates');  // save template to file model on server
},

// add template to exisiting array
setStyleTemplate : function (template) {
  this.store.styleTemplates.push(template);
  this.save('styleTemplates');
},

// get single template based on uuid (or other key)
getStyleTemplate : function (uuid) {
  var template = _.find(this.getStyleTemplates(), function (t) {
     return t.uuid == uuid;
  });
  return template;
},

// template can look like anything, since it's stored as JSON string, but should contain at least:
var template = {
   uuid : Wu.Util.guid('style-template'), // "style-template-23424-asddsa-23223-asdasd"
   timestamp : Date.now(),
   carto : [object], // should be non-stringified json2carto object
   createdBy : app.Account.getUuid(), // uuid of user that created template
   // etc
}
```
- get and set styles wherever you want, eg. creating a new dropdown in [styler.js](https://github.com/systemapic/systemapic.js/blob/master/js/src/chrome/settings/styler.js)

**Comment by knutole** [comment]
jeg har begynt på dette

**Comment by knutole** [comment]
Inject `carto` to styler, in for example [chrome.settings.styler.js](https://github.com/systemapic/systemapic.js/blob/master/js/src/chrome/settings/chrome.settings.styler.js#L80)

``` javascript
var carto = {
  enabled: true, 
  color: Object, 
  opacity: Object, 
  pointsize: Object
}
this._pointStyler.setCarto(carto);
```

Get/Set style from file with get/set functions above.

**Comment by jorgenevil** [comment]
Nice! :)

**Comment by knutole** [comment]
OK, I've added functions described above. Should be ready to try out, by using `this._pointStyler.setCarto(carto)`.  You can do `this._pointStyler.carto()` which will return carto object, so you can see to see what it should look like.

**Comment by knutole** [comment]
See file changes here: 
https://github.com/systemapic/systemapic.js/commit/12840f3d436378a983e5f1a3f6fd65f096b3001e
and here https://github.com/systemapic/wu/commit/8dcca6904aec318a9615f39e94e9b45dde8de138
