### ISSUE TITLE
Css bugs on iPhone 6+

### ISSUE THREAD

**Issue by jorgenevil** [systemapic/systemapic.js#73]
Input fields not working (not possible to type in them)

![](http://i.imgur.com/P4j0nPU.jpg)

Overlapping popup/legend

![](http://i.imgur.com/qrfYir9.jpg)

Searcher goes off screen

![](http://i.imgur.com/b31ysEt.jpg)

Buttons are not leveled. Also, try to use font where possible (not sprite). Reason for this is that sprite gets lowres on retina. If we cannot find icons in awesome fonts, we can make our own systemapic icon font kit from vector drawn icons. Not very hard to do.

![](http://i.imgur.com/K9St6yv.jpg)

Enable complete collapse of legend on phone - it takes up almost the whole screen - on iPhone 6+!!!

![](http://i.imgur.com/2RjCOkO.jpg)

![](http://i.imgur.com/jkTU7qa.jpg)

Sometimes the page crashes on iphone. Too many requests???

![](http://i.imgur.com/lPVUfBL.jpg)

One legend looks off.

![](http://i.imgur.com/QjRgOJM.jpg)

**Comment by jorgenevil** [comment]
See these links for creating icons:

https://icomoon.io/app/
http://www.sitepoint.com/create-an-icon-font-illustrator-icomoon/

**Comment by knutole** [comment]
@jorgenevil Denne overriden funker ikke. Må huske at det er andre events enn click (som `keyup`, `keydown`, etc.)  Så har satt det tilbake til originalen. (Funker ikke med `keyup` events slik det er nå, bl.a.)

https://github.com/systemapic/systemapic.js/blob/master/js/src/core/class.js#L1639:

``` javascript
    // OBS!!!

            // From Jørgen: I've changed this code, so that there is an automatic fallback to 
            // touchstart for click events. I've done this so that we don't have to change the
            // whole code for touch devices, but perhaps it needs to be written elsewhere?

            // Check with Knut Ole :)

            // This is the original one...
            this._on(obj, types[i], fn, context);

            // This is a fallback for mobile/touch devices...

            // // App doesn't exist on login page...
            // if ( !app ) {

            //  this._on(obj, 'click', fn, context);

            // } else {

            //  if ( app.isMobile && types[i] == 'click') { //  || types[i] == 'mousedown' 
            //      var type = 'touchstart';
            //  } else {
            //      var type = types[i];
            //  }

            //  this._on(obj, type, fn, context);

            // }
```
