### ISSUE TITLE
 a few legend bugs

### ISSUE THREAD

**Issue by knutole** [systemapic/systemapic.js#74]
A few bugs on legend:

When uploading new layer, the legend is not created immediately. This is normal. 
- [x] However, when clicking "Update Style", legend is still not created. On reload, correct legend is there (or perhaps just turning layer on/off).
- [x] Perhaps change text "No leged!" til "Create legend in Styler"
- [x] Switch-button is in on-position, even when turning off. 
- [x] Not possible to turn legend back on.
- [x] Perhaps actually add the default legend immediately?
- [ ] Layermenu jumps a lot when selecting layer, because of legend box changing size. This is partly due to layermenu being scrolled to top again when clicking (so jump is extra big when user had already scrolled down in layermenu).

![screen shot 2016-02-13 at 10 22 44 pm](https://cloud.githubusercontent.com/assets/2197944/13030142/62cf0a8c-d2a0-11e5-9eaf-93664351109f.png)

![screen shot 2016-02-13 at 10 17 26 pm](https://cloud.githubusercontent.com/assets/2197944/13030098/996e399c-d29f-11e5-81ea-8689719df343.png)
![screen shot 2016-02-13 at 10 17 15 pm](https://cloud.githubusercontent.com/assets/2197944/13030100/99733712-d29f-11e5-8b12-4ba77c6312e8.png)
![screen shot 2016-02-13 at 10 16 52 pm](https://cloud.githubusercontent.com/assets/2197944/13030099/99721abc-d29f-11e5-8637-a105668f03fd.png)

![screen shot 2016-02-13 at 10 23 59 pm](https://cloud.githubusercontent.com/assets/2197944/13030147/87630ee8-d2a0-11e5-9dc2-97d1c21f285c.png)

![screen shot 2016-02-13 at 10 26 13 pm](https://cloud.githubusercontent.com/assets/2197944/13030156/d549b9e0-d2a0-11e5-818a-9465318e1f19.png)

**Comment by jorgenevil** [comment]
> However, when clicking "Update Style", legend is still not created. On reload, correct legend is there (or perhaps just turning layer on/off).

Agree. I tried to fix this, but you suggested that we left it separated, as the legend box does not have anything to do with styler. I'll create a listener for it – that's the best way, right?

> Perhaps actually add the default legend immediately?

Sure, but I think this has to be done server side, as the layer is created from a model of some sort? It comes with a default style sheet, and legend should be created there as well.

> Layermenu jumps a lot when selecting layer, because of legend box changing size. This is partly due to layermenu being scrolled to top again when clicking (so jump is extra big when user had already scrolled down in layermenu).

True, if you have a lot of layers. Any suggestions?

**Comment by knutole** [comment]
hvorfor ikke bare putte den legenden som er lagd i styler inn i legend box istedet for teksten? 

det er forresten bare å lage en route for å hente default legend fra api.

**Comment by jorgenevil** [comment]
Teksten i legend boxen er der fordi det ikke har vært laget noen legend før – dvs. at den ikke lages av styler'n, men dukker opp hvis laget ikke har noen legend properties (den kommer som blank). 

Og problemet med å oppdatere legend i legend boxen, noe vi bør gjøre når en ny style saves, slik at man ikke må skru laget av og på for å få opp endringene, er:

a) laget man styler trenger ikke nødvendigvis å være lagt til som lag, og da er det heller ikke naturlig at legend oppdateres i den boxen.

b) man kan ha et annet lag valgt enn det laget man styler, og bør da ikke oppdatere legend box.

Ikke umulig å løse selvfølgelig, men heller ikke gjort som en quick fix.

**Comment by knutole** [comment]
quick fix er å fyre en legendUpdated event i styler og lytte i legend box. hvis samme layer, oppdater legend. 

enig at det er ryddigere å lage legend på server side - client bør isåfall spørre server om legend separat.

**Comment by jorgenevil** [comment]
Ja, sure. Event i tror jeg er tingen.

Og det med legend fra server kan jeg se på hvor default CartoJson kommer fra - for et "blankt" lag kommer med CartoJson objekt, og et tomt felt hvor legend havner. Det er naturlig at begge disse har default verdier.

**Comment by knutole** [comment]
@jorgenevil  Angående server-legends:
- Ser ut til at det allerede er noe server-genererte legends (gammel kode?)... `control.cartocss.js` spør server om legends, husker vi genererte noen png'er der før. 

Stack-trace:
- control.cartocss.js https://github.com/systemapic/systemapic.js/blob/master/js/src/controls/control.cartocss.js#L765
- model.layers.js https://github.com/systemapic/systemapic.js/blob/master/js/src/models/model.layers.js#L509
- api.js https://github.com/systemapic/systemapic.js/blob/master/js/src/core/api.js#L76
- routes.js https://github.com/systemapic/wu/blob/master/routes/routes.js#L979
- api.legend.js https://github.com/systemapic/wu/blob/master/api/api.legend.js#L46

osv.. :)
