### ISSUE TITLE
Timeseries-columns should be off by default for Popup

### ISSUE THREAD

**Issue by knutole** [systemapic/systemapic.js#79]
So we can avoid this:

![screen shot 2016-02-14 at 9 38 00 pm](https://cloud.githubusercontent.com/assets/2197944/13036281/4a8ffd8c-d363-11e5-95ef-16ea429a5b94.png)
![screen shot 2016-02-14 at 9 38 54 pm](https://cloud.githubusercontent.com/assets/2197944/13036284/5d3121aa-d363-11e5-8de2-74c07f1303b1.png)

**Comment by jorgenevil** [comment]
How is this going? Do you still get this? Or was it connected to the layer (that it was stored)?

**Comment by jorgenevil** [comment]
@knutole: do you still get this?

**Comment by knutole** [comment]
All good, closing.
