### ISSUE TITLE
Layermenu overflow when lots of layers

### ISSUE THREAD

**Issue by knutole** [systemapic/systemapic.js#83]
![screen shot 2016-02-15 at 3 01 25 pm](https://cloud.githubusercontent.com/assets/2197944/13050645/09ae2360-d3f5-11e5-94b0-b58ce97ef329.png)

Goes all the way to bottom of screen. Should have some padding.

**Comment by knutole** [comment]
@IgorZiegler Need to add some padding on the bottom.

**Comment by jorgenevil** [comment]
This is fixed.
