### ISSUE TITLE
Add filters to invite dropdowns

### ISSUE THREAD

**Issue by knutole** [systemapic/systemapic.js#89]
Need to implement sorting (like [this](https://github.com/systemapic/systemapic.js/issues/19)) also here.

![screen shot 2016-02-16 at 9 19 08 am](https://cloud.githubusercontent.com/assets/2197944/13070638/59ef94aa-d48e-11e5-8b17-f271f97b22d4.png)
![screen shot 2016-02-16 at 9 19 01 am](https://cloud.githubusercontent.com/assets/2197944/13070641/5b9b44a2-d48e-11e5-866c-98873456f98c.png)

![screen shot 2016-02-16 at 9 19 24 am](https://cloud.githubusercontent.com/assets/2197944/13070650/6a0123ea-d48e-11e5-94fc-a2de5719ccb8.png)

**Comment by jorgenevil** [comment]
Having problems with inviting to projects...

I choose Knut from the list
![screen shot 2016-02-16 at 7 19 22 pm](https://cloud.githubusercontent.com/assets/8961926/13086217/8d28c32e-d4e2-11e5-8f80-12bb8bb8d567.png)

When I click his name, he disappears
![screen shot 2016-02-16 at 7 19 27 pm](https://cloud.githubusercontent.com/assets/8961926/13086225/97add3e8-d4e2-11e5-8e3f-2dae156ff04c.png)

When I change project, Knut is not on the list
![screen shot 2016-02-16 at 7 19 48 pm](https://cloud.githubusercontent.com/assets/8961926/13086230/9ceab7b8-d4e2-11e5-9da3-d4f0a23aba8c.png)

So I have to reload
![screen shot 2016-02-16 at 7 20 00 pm](https://cloud.githubusercontent.com/assets/8961926/13086237/a1c631a4-d4e2-11e5-8111-693ff47de662.png)

**Comment by knutole** [comment]
@jorgenevil Du, jeg klarer ikke å reprodusere denne feilen på beta'en? Kan du sjekke igjen? Og notere her hvis det var noe annet bug også?

**Comment by jorgenevil** [comment]
Yes, it still happens. When I remove Knut as an editor, everything seems fine, but I get this in the consol:

![screen shot 2016-02-16 at 8 41 33 pm](https://cloud.githubusercontent.com/assets/8961926/13088719/b3812baa-d4ed-11e5-932c-d190fc29aace.png)

After having added you to a project, your name appears in the list, but when I _go back_ again to add/remove users (without leaving the project), his name is not on the list.

Then, Knut's name does not appear on the list when I change project:
![screen shot 2016-02-16 at 8 44 08 pm](https://cloud.githubusercontent.com/assets/8961926/13088806/1508bb90-d4ee-11e5-95dc-16d3a8a42127.png)

Try logging in on beta.systemapic.com – user: jorgen@systemapic.com pword:

**Comment by knutole** [comment]
@IgorZiegler Managed to reproduce bug. Need to clear internal array that stores contents of input. 

Steps to reproduce:
1. Add users to input box 
2. click (X) or update
3. open fullscreen window again.  you'll see that it remembers from last time. 

So need to clear the local array that remembers what's in the list. You know what to do:)

**Comment by knutole** [comment]
@IgorZiegler Did you fix this? Can we close?

**Comment by IgorZiegler** [comment]
@knutole fixed here https://github.com/systemapic/systemapic.js/pull/132 you can check it on dev3
