### ISSUE TITLE
Minor bug in styler: empty input says "NaN"

### ISSUE THREAD

**Issue by jorgenevil** [systemapic/systemapic.js#91]
![screen shot 2016-02-16 at 11 25 22 am](https://cloud.githubusercontent.com/assets/8961926/13073626/139adcaa-d4a0-11e5-9b85-b7769da2b908.png)

**Comment by IgorZiegler** [comment]
@knutole closed?

**Comment by knutole** [comment]
ask @jorgenevil ? btw, @jorgenevil , make sure you commit with  `--author=jorgen@systemapic.com`

**Comment by jorgenevil** [comment]
I did: `git commit -m "fixes #91" --author=jorgen@systemapic.com`

**Comment by knutole** [comment]
yeah, no prob. it's just not enough for github (see above) - but no matter.
