### ISSUE TITLE
Projects: see how many you have shared with

### ISSUE THREAD

**Issue by jorgenevil** [systemapic/systemapic.js#96]
- [ ] It would have been nice to see how many people you have shared your project with, right next to the project name, like the way you see if it's public or not.
- [ ] If you collaborate on a project, it could also be cool to see which projects that's been changed since last time you visited, marked with a color.

![ss](https://cloud.githubusercontent.com/assets/8961926/13077776/2ddc6d2a-d4bb-11e5-962c-84c2e0e011b1.gif)

**Comment by knutole** [comment]
YES, that's nice :+1:
